apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-web-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /tmp/web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-web-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
